### ISSUE TITLE
Why do I need to install EntityFrameworkCore package for scaffolding a page?

### ISSUE THREAD

**Issue by thomaslevesque** [dotnet/Scaffolding#1437]
## Steps to reproduce:

Run this command on a project that isn't using EntityFramework Core
```
dotnet aspnet-codegenerator identity --files Account.ExternalLogin
```

## Expected behavior:

It should scaffold the [ExternalIdentity](https://github.com/dotnet/aspnetcore/blob/ac2dec9d4c2b988c9c6f8032beee006599641355/src/Identity/UI/src/Areas/Identity/Pages/V4/Account/ExternalLogin.cshtml.cs) page

## Actual behavior:

It tells me to install these two packages:
- Microsoft.EntityFrameworkCore.Design
- Microsoft.EntityFrameworkCore.SqlServer

But I'm not using EF Core... I'm using a custom UserStore and RoleStore (based on Cosmos DB)
And anyway, this page doesn't use EF Core at all, so there's no need for these packages

### Target framework(s):
.NET Core 3.1

### Package version of Microsoft.AspNetCore.App or Microsoft.AspNetCore.All (if applicable):
3.1.9

### Package version of Microsoft.VisualStudio.Web.CodeGeneration.Design - this may be added to your project by scaffolding:
3.1.4

**Comment by thomaslevesque** [comment]
Also, why does it generate AuthPadIdentityDbContext and IdentityHostingStartup? I only asked for ExternalLogin!

**Comment by BrightSoul** [comment]
+1
Since ASP.NET Core Identity does not require EFCore, the scaffolding tool should NOT as well. I'm using a custom UserStore in a project that's based on ADO.NET and I was forced to install thos packages @thomaslevesque mentioned only to remove them after the scaffolding was done.

The tool should allow a `--userStore` parameter or, better yet, a `--userClass` parameter which is really the only essential requirement for scaffolding. Example:
```
dotnet aspnet-codegenerator identity --userClass "MyProject.Models.ApplicationUser, MyProject "
```

**Comment by deepchoudhery** [comment]
Mostly fixed with the new dotnet-scaffold tool. Blog [here](https://devblogs.microsoft.com/dotnet/introducing-dotnet-scaffold/)
- no extra identity classes
- EfCore.Tools package is installed, in case you need to activate DbContext
- A different EF package is installed based on the DbProvider picked
