### ISSUE TITLE
Error while try to add saffloding "startIndex cannot be larger than length of string. (Parameter 'startIndex')"

### ISSUE THREAD

**Issue by panupong-sudj** [dotnet/Scaffolding#2030]
![image](https://user-images.githubusercontent.com/78843048/192421687-e88fe7ad-bf4b-4371-a469-5d1f8b92f523.png)

i have update all packet to lastest version

**Comment by deepchoudhery** [comment]
Hey,
What was the scaffolding operation you were performing? Trying to track down what Substring operation is causing this.

Thanks,
Deep

**Comment by Coder686375** [comment]
I see a similar error in Visual Studio and the CLI when attempting to scaffold identity.

```
C:\MyProject>dotnet aspnet-codegenerator identity --useDefaultUI
Building project ...
Finding the generator 'identity'...
Running the generator 'identity'...
Length cannot be less than zero. (Parameter 'length')
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.<BuildCommandLine>b__6_0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.ActionInvoker.Execute(String[] args)
   at Microsoft.VisualStudio.Web.CodeGeneration.CodeGenCommand.Execute(String[] args)
RunTime 00:00:12.70
```

I've tried .NET 5.0, 6.0, and 7.0 as well as several recent versions of `Microsoft.VisualStudio.Web.CodeGeneration.Design` (including 7.0.1). It seems specific to the project because scaffolding on a simple project does work. I've seen this [mentioned here](https://learn.microsoft.com/en-us/answers/questions/931245/identity-scaffolding-in-net-core-60-gives-error-me.html) as well.

**Comment by Coder686375** [comment]
I found that if I create a Startup.cs file with an empty Startup class then it works. The problem may be in this Substring: https://github.com/dotnet/Scaffolding/blob/9b5639fbb2dd1eaea5be1570e00bd4dee6d73b78/src/Shared/Microsoft.DotNet.Scaffolding.Shared/Project/ProjectModifierHelper.cs#L93

**Comment by deepchoudhery** [comment]
Will take a look soon ty.
