### ISSUE TITLE
Scaffolding fails with vague error if Model has a private property mapped in the DbContext.

### ISSUE THREAD

**Issue by prafullbhosale** [dotnet/Scaffolding#683]
Having a model class and DbContext as below causes scaffolding (razor pages/ Views using EF) to fail with an error message: 
```
"Cannot perform runtime binding on a null reference"
```

**Model class**
```cs
    public class Car
    {
        public int ID { get; set; }
        private string Name { get; set; }
        public string Model { get; set; }
    }
```
**DbContext class**
```cs
    public class CarsContext : DbContext
    {
        public CarsContext (DbContextOptions<CarsContext> options)
            : base(options)
        {

        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Car>().Property("Name");
        }

        public DbSet<WebApplication11.Models.Car> Car { get; set; }
    }
```

**Comment by DavidChennells** [comment]
I was hit by precisely this problem today and wasted two hours before isolating the problem to this cause.  (This issue is still not registering in the search results.)

My IEntityTypeConfiguration<T>.Configure(EntityTypeBuilder<T> entityBuilder) code is interpreted perfectly at run-time.  However, when I went to use the current scaffolding tool in VS 15.7.0 Preview 1.0 (Add => New Scaffolded item => "MVC Controller with views, using Entity Framework") I received the same error as above.  Precisely the same problem occurs with the OnModelCreating(ModelBuilder modelBuilder) method, as above.

When you are dealing with thousands of lines of mapping code, it is not particularly pleasant isolating the problem arising from a meaningless error message with a black box tool such as a scaffolder to a single call.

This brings a few questions to mind:
- How is the (unit + integration) test coverage going with the, umm, "core" EF Core scenarios, in this case, "Backing Fields - Fields without a property," as it's described in the docs?
- Would you think of including in your error messages certain meta-data about the user's calls (such as the name of the element and user code line number causing the problem)?
- Any chance of adding a verbose/diagnostic logging option or a (published) way to attach a debugger, or do you have this already for scaffolding?
- Would you consider adding a ReadMe on your main page outlining troubleshooting methods for quasi-silent failures of this nature?  (Example, how to compile and run the scaffolder code on your dev computer?)
- I see this issue has had one participant for the past six weeks.  Any chance that it will be assigned to a dev to resolve in time for 2.1 RTM?

As far as workarounds, in case others are experiencing the same problem, I'm enclosing all private field mappings in what is essentially conditional tests, in an if statement that reaches a static constant.  Like this:

            if (EntityBuildingOptions.ConfigurePrivateFields)
            {
                entityBuilder.Property("_isDeleted")
                    .UsePropertyAccessMode(PropertyAccessMode.Field)
                    .HasConversion(EntityFrameworkValueConverters.BoolToCharValueConverter)
                    .HasColumnName("deleted_indicator")
                    .HasColumnType("char(1)"); 
            }

(For scaffolding I set that constant to false.)

**Comment by vijayrkn** [comment]
I can still repro this issue. 

![image](https://user-images.githubusercontent.com/3981619/68520826-df490d00-024f-11ea-9812-8af0c05f8287.png)

**Comment by deepchoudhery** [comment]
fixed for dotnet-scaffold, closing., please use the new 'dotnet-scaffold' tool. Blog [here](https://devblogs.microsoft.com/dotnet/introducing-dotnet-scaffold/)
